defaults:
  outputdir: /g/data/hh5/admin/analytics/logs
  # outputdir: dump
  dateformat: '%FT%T'
  remote_host: jenkins
  remote_port: 5432
  local_port: 9107
  # dburl: sqlite:///dump_{local_port}.db
  dburl: postgresql://localhost:{local_port}/grafana
mounts:
  scratch:
    - v45
    - w40
    - w42
    - w97
    - hh5 
    - ua8 
    - e14
    - g40
    - x77 
    - w28 
    - x52 
    - p66 
    - ds2 
    - e53 
    - dt6 
    - y99 
    - nm03
    - k10
    - p73
    - jk72
    - tm70
    - iq82
    - ol01
    - rp23
    - gx60
    - lg87
    - au88
    - nm47
    - xd2
  gdata:
    - v45
    - w40
    - x77 
    - e14 
    - ua8 
    - rq7 
    - p66 
    - g40
    - w42 
    - w97 
    - hh5
    - w28 
    - k10
    - ik11 
    - nm03 
    - cj50 
    - y99
    - p73
    - jk72
    - tm70
    - iq82
    - ol01
    - rp23
    - gx60
    - lg87
    - au88
    - nm47
    - kj13
    - xp65
    - xd2
compute:
  - v45
  - w40
  - w42
  - w97
  - e14
  - g40
  - x77 
  - w28 
  - x52 
  - p66 
  - ds2 
  - e53 
  - dt6 
  - y99 
  - nm03
  - k10
  - jk72
  - tm70
  - iq82
  - ol01
  - rp23
  - gx60
  - lg87
  - au88
  - nm47
  - xd2
